#!/usr/bin/with-contenv bash

_term() {
  echo "Caught SIGTERM signal!"
  echo "Tell Wireguard to shut down."
  #pid=$(pidof wg-quick)
  wg-quick down wg0
  # terminate when the transmission-daemon process dies
  # tail --pid=${pid} -f /dev/null
}

# DELUGE_LOGLEVEL=${DELUGE_LOGLEVEL:-info}

# exec \
#     s6-setuidgid abc /usr/bin/deluged -c /config \
#     -d --loglevel="${DELUGE_LOGLEVEL}"

# exec \
#     s6-setuidgid abc wg-quick up wg0
wg-quick up wg0

# wg-quick up wg0
# trap _term SIGTERM
# wg show
# sleep infinity