#!/usr/bin/with-contenv bash

_term() {
  echo "Caught SIGTERM signal!"
  echo "Tell Wireguard to shut down."
  #pid=$(pidof wg-quick)
  wg-quick down wg0
  # terminate when the transmission-daemon process dies
  # tail --pid=${pid} -f /dev/null
}

# exec s6-setuidgid abc wg-quick up wg0
exec wg-quick up wg0
# does not run as a daemon and this script seems to be called continously
sleep infinity
